In [23]:
import pandas as pd

In [24]:
df = pd.read_csv("./cutline_data.csv")

In [25]:
display(df)

     공고연도 공고차수                       단지명 공급유형 신청자격  당첨순위 심사단계  커트라인점수
0    2026   1차                   리마크빌 구의  39A  신혼Ⅰ     3   서류       3
1    2026   1차                   리마크빌 구의  39B  신혼Ⅰ     3   서류       3
2    2026   1차            해링턴플레이스 노원 센트럴   22   청년     2   서류       6
3    2026   1차            해링턴플레이스 노원 센트럴   23   청년     2   서류       8
4    2026   1차         어바니엘 위드 더 스타일 충정로   16   청년     1   서류       8
..    ...  ...                       ...  ...  ...   ...  ...     ...
389  2025   1차                   세이지움 상봉   48  신혼Ⅰ     1   최종       6
390  2025   1차  용산 남영역 루미니(용산 롯데캐슬 헤리티지)   23   청년     1   최종       8
391  2025   1차  용산 남영역 루미니(용산 롯데캐슬 헤리티지)   39  신혼Ⅰ     1   최종       3
392  2025   1차  용산 남영역 루미니(용산 롯데캐슬 헤리티지)   49  신혼Ⅱ     1   최종       4
393  2025   1차                센터스퀘어 서울대점  44C  신혼Ⅱ     3   최종       2

[394 rows x 8 columns]

In [26]:
print("\n[심사단계 및 유형별 비교 피벗 테이블]")
display(df.groupby(['심사단계', '신청자격'])['커트라인점수'].mean().unstack())

[심사단계 및 유형별 비교 피벗 테이블]

신청자격    셰어형(팀)       신혼Ⅰ  신혼Ⅱ        청년     청년(남)  청년(셰어)  청년(여)
심사단계
서류         NaN  2.750000  4.0  6.915888       NaN     7.0    NaN
최종    7.666667  2.913793  2.5  6.824675  4.333333     NaN   3.75